services:
  db:
    image: mariadb:10.11
    container_name: edulatina_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secure_root_password_123
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodle_password_123
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # ONLY ADDITION: RAM limit for database
    deploy:
      resources:
        limits:
          memory: 200M

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: edulatina_php
    restart: unless-stopped
    environment:
      - MOODLE_URL=http://3.140.95.210
      - MOODLE_DATAROOT=/var/www/moodledata
      - DB_HOST=db
      - DB_NAME=moodle
      - DB_USER=moodleuser
      - DB_PASS=moodle_password_123
    volumes:
      - ./moodle-data:/var/www/html
      - ./moodledata:/var/www/moodledata
      - ./config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    # ONLY ADDITION: RAM limit for Moodle PHP
    deploy:
      resources:
        limits:
          memory: 200M

  web:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: edulatina_web
    restart: unless-stopped
    environment:
      - MOODLE_URL=http://3.140.95.210
    ports:
      - "80:80"
    volumes:
      - ./moodle-data:/usr/local/apache2/htdocs/moodle
      - ./config/apache/moodle.conf:/usr/local/apache2/conf/extra/moodle.conf
    depends_on:
      - php
    command: >
      sh -c "echo 'Include conf/extra/moodle.conf' >> /usr/local/apache2/conf/httpd.conf && 
             httpd-foreground"
    # ONLY ADDITION: RAM limit for Apache
    deploy:
      resources:
        limits:
          memory: 100M

  wordpress_test:
    image: wordpress:6.4-apache
    container_name: edulatina_wordpress_test
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=moodleuser
      - WORDPRESS_DB_PASSWORD=moodle_password_123
      - WORDPRESS_DB_NAME=wordpress_test
      - WORDPRESS_TABLE_PREFIX=wp_
    volumes:
      - ./wordpress-test-data:/var/www/html
    depends_on:
      - db
    # ONLY ADDITION: RAM limit for WordPress
    deploy:
      resources:
        limits:
          memory: 300M

networks:
  default:
    name: edulatina_network
